### PR TITLE
Added a naive implementation for functional components

### PR DESCRIPTION
**Pull request by zerkms**
This is the naive and straightforward implementation for functional components, see #13

Technically one might improve it if the detection if the component is functional and if the wrapping it in a class in necessary. Practically there is no non-heuristic based solution at the moment, and in the other libraries it's implemented as something like https://github.com/acdlite/recompose/blob/master/src/packages/recompose/isReferentiallyTransparentFunctionComponent.js

I think that for optimisation purposes the solution might be borrowed.

### CODE REVIEW

**Comment by jurassix** [comment]
@zerkms Thanks for the PR. Code looks great. 

The only piece I'm worried about is a peer dependency on React. I'll think through some alternative; this may be the best we can do.

**Comment by zerkms** [comment]
@jurassix I have made some more research and experiments, and have relaxed the peer dependency to "any version".

It makes sense since:

* For react components < v0.13 the mixin must be used
* For react components >= v0.13 the HoC wrapper must be used

Which means the library supports any recent versions of reactjs (I have only checked the 0.12, 0.13 and 0.14), but you still need to have a peer dependency anyway, since it's a library for react anyway.

**Comment by jurassix** [comment]
Thanks for the info. I think we need to specify the version range for React; a blank version seems a little odd to me. I've seen `*` when you just wanted latest version, not sure it means any version though?

What if we use the `React.createClass` API in the HOC instead of `class X extends React.Component`?  It seems like we could then easily set the peerDependency "react": ">=0.11" or whatever we think is the lowest React version people will be using? Assuming `React.createClass` and `React.createElement` are both in that React version.

Any thoughts on this approach?

**Comment by zerkms** [comment]
> I've seen * when you just wanted latest version, not sure it means any version though?

For the peer dependency `*` and an empty version mean the same: any version must be installed.

> What if we use the React.createClass API in the HOC instead of class X extends React.Component?

This was my initial thought and I even implemented that. But then I realised that HoCs make only sense in react>=0.13 so it's safe to implement it so.

> It seems like we could then easily set the peerDependency "react": ">=0.11" or whatever we think is the lowest React version people will be using

I don't think there is a practical reason to restrict a react version at the moment: the library did not have any limitations before, so I would suggest to stay with `*` for until someone reports that some ancient version does not work.

**Comment by jurassix** [comment]
Thx for the input. PR merged as is. I'll update once published to npm.

**Comment by jurassix** [comment]
published to npm as v0.9.3

**Comment by zerkms** [comment]
Great, thanks :-)

**Pull request merged**
